### ISSUE TITLE
Different number of lines in some files

### ISSUE THREAD

**Issue by Dronte** [MicrosoftTranslator/NTREX#3]
Some files have not 1997 lines:

    1998 newstest2019-ref.fij.txt
    1998 newstest2019-ref.tgk-Cyrl.txt
    1998 newstest2019-ref.zul.txt
    2019 newstest2019-ref.wol.txt
    2031 newstest2019-ref.urd.txt
    2042 newstest2019-ref.vie.txt

Am i right, this doesn't allow to match them with newstest2019-src.eng.txt ?

**Comment by cfedermann** [comment]
Thanks, I'll have a look...

**Comment by Smu-Tan** [comment]
Any updates? @cfedermann

**Comment by Smu-Tan** [comment]
> Some files have not 1997 lines:
> 
> ```
> 1998 newstest2019-ref.fij.txt
> 1998 newstest2019-ref.tgk-Cyrl.txt
> 1998 newstest2019-ref.zul.txt
> 2019 newstest2019-ref.wol.txt
> 2031 newstest2019-ref.urd.txt
> 2042 newstest2019-ref.vie.txt
> ```
> 
> Am i right, this doesn't allow to match them with newstest2019-src.eng.txt ?

It seems like there're several empty lines in Urdu file, after deleting them it is back to the same number of lines. Note: I did not check the other languages you mentioned.

**Comment by icaswell** [comment]
This is fixed by https://github.com/MicrosoftTranslator/NTREX/pull/7

**Comment by Numeri** [comment]
@cfedermann Can Microsoft get this fixed/merge the PR? I'm sure I'm not the only one who used this in code that silently failed (it didn't check that the lengths of the two files were equal). I only caught this because my reference-free metrics for `eng-vie` were significantly higher than any reference-based metrics.

**Comment by kocmitom** [comment]
Hi, thank you for creating an issue. There were some empty lines. It should be fixed now. 
A sidenote, this is not an officially supported Microsoft product.
