### ISSUE TITLE
empty lines in Vietnamese

### ISSUE THREAD

**Issue by Yaoming95** [MicrosoftTranslator/NTREX#5]
Thanks a lot for your test set! 
I noticed that some lines are empty in https://github.com/MicrosoftTranslator/NTREX/blob/main/NTREX-128/newstest2019-ref.vie.txt   . Is the translation here normal?

**Comment by icaswell** [comment]
this is fixed by https://github.com/MicrosoftTranslator/NTREX/pull/7

**Comment by kocmitom** [comment]
Hi, thank you for creating an issue. It should be fixed now.
