### ISSUE TITLE
Wolof seems to have incorrect no. of lines

### ISSUE THREAD

**Issue by Remorax** [MicrosoftTranslator/NTREX#9]
Wolof seems to have 2019 lines, compared to the other lines that have 1997. I tried filtering for empty lines, and it does not seem to make a difference - unlike other files, that actually had many empty lines!

Seems to be an outlier, can someone please look into this?

**Comment by kocmitom** [comment]
Hi, thank you for creating an issue. There were some empty lines. It should be fixed now.
